# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20190323_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
