# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20190323_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='image',
            new_name='bus_image',
        ),
    ]
