# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20190323_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
    ]
