# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_category_location_neighbourhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
